-- Generated by Oracle SQL Developer Data Modeler 18.4.0.339.1532
--   at:        2019-08-26 22:24:38 CEST
--   site:      SQL Server 2012
--   type:      SQL Server 2012

CREATE TABLE advertisement.dbo.gra (
    id_gra           NUMERIC(28) PRIMARY KEY,
    nazwa            VARCHAR(20),
    gatunek          VARCHAR(20),
    cena             NUMERIC(28),
    liczba_postaci   NUMERIC(28)
);

CREATE TABLE advertisement.dbo.platforma (
    id_platforma         NUMERIC(28) PRIMARY KEY,
    nazwa                VARCHAR(30),
    liczba_graczy        NUMERIC(28),
    liczba_piratow       NUMERIC(28)
);

CREATE TABLE advertisement.dbo.poprawka (
    id_poprawka        NUMERIC(28) PRIMARY KEY,
	id_gra             NUMERIC(28),
	id_wersja_poprawki NUMERIC(28),
    nazwa_kodowa       VARCHAR(30),
    koszt              NUMERIC(28),
    priorytet          NUMERIC(28)
);

CREATE TABLE advertisement.dbo.promocja (
    id_promocja         NUMERIC(28) PRIMARY KEY,
	id_gra              NUMERIC(28),
	id_rodzaj_promocji  NUMERIC(28),
    nazwa_kodowa        VARCHAR(30),
    koszt               NUMERIC(28),
    zasieg              NUMERIC(28),
);

CREATE TABLE advertisement.dbo.rodzaj_promocji (
    id_rodzaj_promocji     NUMERIC(28) PRIMARY KEY,
    nazwa                  VARCHAR(30),
    grupa_docelowa         VARCHAR(30),
    liczba_skandali        NUMERIC(28)
);

CREATE TABLE advertisement.dbo.wersja_poprawki (
    id_wersja_poprawki     NUMERIC(28) PRIMARY KEY,
    nazwa                  VARCHAR(30),
    liczba_kolizji         NUMERIC(28)
);

CREATE TABLE advertisement.dbo.wydanie (
	id_wydanie     NUMERIC(28) PRIMARY KEY,
    id_gra         NUMERIC(28),
    id_platforma   NUMERIC(28),
    nazwa_kodowa   VARCHAR(30),
    rok_premiery   NUMERIC(28),
    koszt          NUMERIC(28),
);
