-- Generated by Oracle SQL Developer Data Modeler 18.4.0.339.1532
--   at:        2019-08-26 22:24:38 CEST
--   site:      SQL Server 2012
--   type:      SQL Server 2012

CREATE TABLE development.dbo.dodatek (
    id_dodatek     NUMERIC(28) PRIMARY KEY,
    nazwa          VARCHAR(20),
    cena           NUMERIC(28),
    liczba_broni   NUMERIC(28)
);

CREATE TABLE development.dbo.gra (
    id_gra           NUMERIC(28) PRIMARY KEY,
    nazwa            VARCHAR(20),
    gatunek          VARCHAR(20),
    cena             NUMERIC(28),
    liczba_postaci   NUMERIC(28)
);

CREATE TABLE development.dbo.poprawka (
    id_poprawka        NUMERIC(28) PRIMARY KEY,
	id_gra             NUMERIC(28),
	id_wersja_poprawki NUMERIC(28),
    nazwa_kodowa       VARCHAR(30),
    koszt              NUMERIC(28),
    priorytet          NUMERIC(28)
);

CREATE TABLE development.dbo.produkcja (
    id_produkcja       NUMERIC(28) PRIMARY KEY,
	id_studio          NUMERIC(28),
	id_gra             NUMERIC(28),
    nazwa_kodowa       VARCHAR(30),
    rok_rozpoczecia    NUMERIC(28),
    koszt              NUMERIC(28), 
);

CREATE TABLE development.dbo.studio (
    id_studio            NUMERIC(28) PRIMARY KEY,
    nazwa                VARCHAR(30),
    liczba_pracownikow   NUMERIC(28),
    liczba_dzialow       NUMERIC(28),
    siedziba             VARCHAR(30)
);

CREATE TABLE development.dbo.wersja_poprawki (
    id_wersja_poprawki     NUMERIC(28) PRIMARY KEY,
    nazwa                  VARCHAR(30),
    liczba_kolizji         NUMERIC(28)
);

CREATE TABLE development.dbo.wprowadzenie_dodatku (
	id_wprowadzenie_dodatku   NUMERIC(28) PRIMARY KEY,
    id_dodatek                NUMERIC(28),
    id_studio                 NUMERIC(28),
	nazwa_kodowa              VARCHAR(30),
    rok_wprowadzenia          NUMERIC(28),
	koszt                     NUMERIC(28),
);