-- Generated by Oracle SQL Developer Data Modeler 18.4.0.339.1532
--   at:        2019-08-26 22:23:19 CEST
--   site:      SQL Server 2012
--   type:      SQL Server 2012

CREATE TABLE stage.dbo.d_dodatek (
    id_dodatek                       NUMERIC(28),
    nazwa                            VARCHAR(20),
    cena                             NUMERIC(28),
    source                           NUMERIC(28),
	timestamp                        datetime,
	liczba_broni                     NUMERIC(28)
);

CREATE TABLE stage.dbo.d_gra (
    id_gra                   NUMERIC(28),
    nazwa                    VARCHAR(20),
    gatunek                  VARCHAR(20),
    cena                     NUMERIC(28),
    source                   NUMERIC(28),
    timestamp                datetime,
	liczba_postaci           NUMERIC(28)
);

CREATE TABLE stage.dbo.a_gra (
    id_gra                   NUMERIC(28),
    nazwa                    VARCHAR(20),
    gatunek                  VARCHAR(20),
    cena                     NUMERIC(28),
    source                   NUMERIC(28),
    timestamp                datetime,
	liczba_postaci           NUMERIC(28)
);

CREATE TABLE stage.dbo.a_platforma (
    id_platforma                         NUMERIC(28),
    nazwa                                VARCHAR(30),
    liczba_graczy                        NUMERIC(28),
    source                               NUMERIC(28),
    timestamp                            datetime,
	liczba_piratow                       NUMERIC(28)
);

CREATE TABLE stage.dbo.d_poprawka (
    id_poprawka                        NUMERIC(28),
	id_gra                             NUMERIC(28),
	id_wersja_poprawki                 NUMERIC(28),
    koszt                              NUMERIC(28),
    priorytet                          NUMERIC(28),
    source                             NUMERIC(28),
    timestamp                          datetime,
	nazwa_kodowa                       VARCHAR(30),
);

CREATE TABLE stage.dbo.a_poprawka (
    id_poprawka                        NUMERIC(28),
	id_gra                             NUMERIC(28),
	id_wersja_poprawki                 NUMERIC(28),
    koszt                              NUMERIC(28),
    priorytet                          NUMERIC(28),
    source                             NUMERIC(28),
    timestamp                          datetime,
	nazwa_kodowa                       VARCHAR(30),
);

CREATE TABLE stage.dbo.d_produkcja (
    id_produkcja                         NUMERIC(28),
	id_studio                            NUMERIC(28),
	id_gra                               NUMERIC(28),
    rok_rozpoczecia                      NUMERIC(28),
    koszt                                NUMERIC(28),
    source                               NUMERIC(28),
    timestamp                            datetime,
	nazwa_kodowa                         VARCHAR(30),
);

CREATE TABLE stage.dbo.a_promocja (
    id_promocja                        NUMERIC(28),
	id_gra                             NUMERIC(28),
	id_rodzaj_promocji                 NUMERIC(28),
    koszt                              NUMERIC(28),
    zasieg                             NUMERIC(28),
    source                             NUMERIC(28),
    timestamp                          datetime,
	nazwa_kodowa                       VARCHAR(30),
);

CREATE TABLE stage.dbo.a_rodzaj_promocji (
    id_rodzaj_promocji                               NUMERIC(28),
    nazwa                                            VARCHAR(30),
    grupa_docelowa                                   VARCHAR(30),
    source                                           NUMERIC(28),
    timestamp                                        datetime,
	liczba_skandali                                  NUMERIC(28)
);

CREATE TABLE stage.dbo.d_studio (
    id_studio                      NUMERIC(28),
    nazwa                          VARCHAR(30),
    liczba_pracownikow             NUMERIC(28),
    liczba_dzialow                 NUMERIC(28),
    source                         NUMERIC(28),
    timestamp                      datetime,
	siedziba                       VARCHAR(30)
);

CREATE TABLE stage.dbo.d_wersja_poprawki (
    id_wersja_poprawki                               NUMERIC(28),
    nazwa                                            VARCHAR(30),
    source                                           NUMERIC(28),
    timestamp                                        datetime,
	liczba_kolizji									 NUMERIC(28)
);

CREATE TABLE stage.dbo.a_wersja_poprawki (
    id_wersja_poprawki                               NUMERIC(28),
    nazwa                                            VARCHAR(30),
    source                                           NUMERIC(28),
    timestamp                                        datetime,
	liczba_kolizji									 NUMERIC(28)
);

CREATE TABLE stage.dbo.d_wprowadzenie_dodatku (
    id_wprowadzenie_dodatku                                    NUMERIC(28),
	id_dodatek                                                 NUMERIC(28),
	id_studio                                                  NUMERIC(28),
    rok_wprowadzenia                                           NUMERIC(28),
    koszt                                                      NUMERIC(28),
    source                                                     NUMERIC(28),
    timestamp                                                  datetime,
	nazwa_kodowa                                               VARCHAR(30),
);

CREATE TABLE stage.dbo.a_wydanie (
    id_wydanie                       NUMERIC(28),
	id_gra                           NUMERIC(28),
	id_platforma					 NUMERIC(28),
    rok_premiery                     NUMERIC(28),
    koszt                            NUMERIC(28),
    source                           NUMERIC(28),
    timestamp                        datetime,
	nazwa_kodowa					 VARCHAR(30),
);
